---

- name: Synchronization of Devices
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Configure device subinterfaces
      with_items:
        - name: Ansible-1
          device:
            - device: ios1
              interface-type: FastEthernet
              interface-num: 0/2
              subif-num: 150
              ip-address: 10.10.150.1
              mask: 255.255.255.0
        - name: Ansible-2
          device:
            - device: xr1
              interface-type: TenGigE
              interface-num: 0/0/0/3
              subif-num: 150
              ip-address: 10.20.150.1
              mask: 255.255.255.0
      nso_config:
        url: http://localhost:8080/jsonrpc
        username: "admin"
        password: "admin"
        data:
          netdevops:vlan:
            - "{{ item }}"
