---

- name: Synchronization of Devices
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Configure CustC tail
      nso_config:
        url: http://localhost:8080/jsonrpc
        username: "admin"
        password: "admin"
        data:
          subif-and-interface:subif-and-interface:
          - name: CustB
            device: "ios1"
            interface-num: 1/3
            subif-num: 150
            ip-address: 10.10.150.1
            mask: 255.255.255.0
