---

- name: Synchronization of Devices
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Configure CustB tail
      nso_config:
        url: http://localhost:8080/jsonrpc
        username: "admin"
        password: "admin"
        data:
          subif-and-routing:subif-and-routing:
          - cust-name: CustB
            subif-num: 175
            device:
            - device-name: ios1
              interface:
              - interface-type: FastEthernet
                interface-num: 1/5
                ip-address: 10.10.175.1
